function buildMotrExecutable()

% Check that compilation has been done, do it if not
% Use parsejpg8 as the canary in the coalmine
if ~isParsejpg8MexFilePresent()
  compileMexFunctions();
end

% figure out where the root of the Ohayon code is
thisScriptFileName=mfilename('fullpath');
thisScriptDirName=fileparts(fileparts(thisScriptFileName));
%mouseStuffRootDirName=thisScriptDirName;

% % determine the current architecture
% archStr=computer('arch');                

% Compile matlab script
exeDirName=fullfile(thisScriptDirName,'bin');
% exeDirName= ...
%   fullfile(mouseStuffRootDirName,'Deploy','MouseTrackProj','src');
if ~exist(exeDirName,'dir')
  mkdir(exeDirName);
end

% Need to add -I and -a options here to pull in all the stuff on the motr
% path in normal operation.  See the script for building the cluster
% executable.

% Invoke mcc to compile the motr executable.
cmdLine= ...
  sprintf(['mcc -m -v -o motr ' ...
           '-d %s ' ...
           'MouseHouse ' ...
           '-a Algorithms.xml ' ...
           '-a DefaultDefaultSegmentationParams.xml ' ...
           '-a hTrain_Callback.m ' ...
           '-a hTrack_Callback.m ' ...
           '-a JobsManager.fig ' ...
           ], ...
           exeDirName);
eval(cmdLine);

% Invoke mcc to compile the catalytic executable.
cmdLine= ...
  sprintf(['mcc -m -v -o catalytic ' ...
           '-d %s ' ...
           'catalytic ' ...
           ], ...
           exeDirName);
eval(cmdLine);

end
